routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('/', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('login_auth');

Route::prefix('portal')
->middleware('auth')
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::get('users/reset-password', 'UsersController@reset_password_form')->name('reset_password_form');
	Route::post('users/reset-password', 'UsersController@reset_password')->name('reset_password');

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('drivers/search', 'DriverController@json_search')->name('json_search');
	Route::resource('drivers', 'DriverController');
	Route::resource('vehicles', 'VehicleController');

	Route::prefix('settings')
	->middleware('AdminAccess')
	->group(function(){
		Route::resource('violation-type', 'ViolationTypeController');
		Route::resource('vehicle-body-type', 'VehicleBodyTypeController');
		Route::resource('fuel', 'FuelController');

		Route::get('users/generate-password', 'UsersController@generate_password')->name('generate_password');
		Route::resource('users', 'UsersController');
	});
	
	Route::get('violations/upload', 'ViolationsController@upload_form')->name('violation_upload');
	Route::post('violations/upload', 'ViolationsController@process_image')->name('violation_process');
	Route::resource('violations', 'ViolationsController');

	Route::prefix('reports')
	->group(function(){
		Route::resource('report-violation', 'ReportViolationController');
	});
});

app/Driver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Driver extends Model
{
     public $table = 'driver';
     public $timestamps = true;

     protected $fillable = ['license_number', 'license_type_id', 'expiry_date', 'agency_code', 'first_name', 'middle_name', 'last_name', 'birth_date', 'gender', 'nationality', 'height', 'weight', 'email', 'address', 'city', 'created_at', 'updated_at'];

     public function license()
     {
     	return $this->hasOne('App\DriverLicenseType', 'id', 'license_type_id');
     }

     public function vehicle()
     {
     	return $this->belongsTo('App\Vehicle', 'id', 'driver_id');
     }

     public function violation()
     {
          return $this->belongsTo('App\Violation', 'id', 'driver_id');
     }



     public function getCompleteLastNameAttribute()
     {
     	return $this->last_name . ', ' . $this->first_name . ' ' . $this->middle_name;
     }

     public function getCompleteFirstNameAttribute()
     {
          return $this->last_name . ', ' . $this->first_name . ' ' . $this->middle_name;
     }
}

resources/views/report/driver-violation-print.blade.php
@extends('layouts.plain')

@section('content')

<h4>Ticket Date - {{ $ticket_date->toDateString() }}</h4>

<table class="table is-bordered is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th>Driver</th>
            <th>Vehicle</th>
            <th>Violation</th>
            <th>Ticketing Officer</th>
            <th>Remarks</th>
        </tr>
    </thead>
    <tbody>
        @foreach($rows as $row)
            <tr>
                <td>{{ $row->driver->complete_last_name }}</td>
                <td>{{ $row->vehicle->plate_number }}</td>
                <td>
                    @foreach($row->list->whereViolationId($row->id)->get() as $violation)
                        <u>{{ $violation->type->name }}</u>
                    @endforeach
                </td>
                <td>{{ $row->user->name }}</td>
                <td>{{ $row->remarks }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

@endsection

resources/views/report/driver-violation.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="#">Reports</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Violation</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            @include('layouts.validation-messages')
            <div class="content">
    
                <form action="{{ $route }}" method="get" target="_blank">
                    <div class="columns">
                        <div class="column is-6">

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="ticket_date">Ticket Date</label>
                                </div>
                                <div class="field-body">
                                    <div class="field is-narrow">
                                        <p class="control">
                                            <input class="input is-normal" type="date" name="ticket_date" id="ticket_date" value="{{ $ticket_date }}">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label"></div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="control">
                                            <button class="button is-info is-normal">Submit</button>
                                            {!! csrf_field() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@push('scripts')

<script type="text/javascript">
</script>
@endpush