routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('/', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('login_auth');

Route::prefix('portal')
->middleware('auth')
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::get('users/reset-password', 'UsersController@reset_password_form')->name('reset_password_form');
	Route::post('users/reset-password', 'UsersController@reset_password')->name('reset_password');

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('drivers/search', 'DriverController@json_search')->name('json_search');
	Route::resource('drivers', 'DriverController');
	Route::resource('vehicles', 'VehicleController');

	Route::prefix('settings')
	->middleware('AdminAccess')
	->group(function(){
		Route::resource('violation-type', 'ViolationTypeController');
		Route::resource('vehicle-body-type', 'VehicleBodyTypeController');
		Route::resource('fuel', 'FuelController');

		Route::get('users/generate-password', 'UsersController@generate_password')->name('generate_password');
		Route::resource('users', 'UsersController');
	});
	
	Route::get('violations/upload', 'ViolationsController@upload_form')->name('violation_upload');
	Route::post('violations/upload', 'ViolationsController@process_image')->name('violation_process');
	Route::resource('violations', 'ViolationsController');

	Route::prefix('reports')
	->group(function(){
		Route::resource('report-violation', 'ReportViolationController');
	});
});

app/Driver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Driver extends Model
{
     public $table = 'driver';
     public $timestamps = true;

     protected $fillable = ['license_number', 'license_type_id', 'expiry_date', 'agency_code', 'first_name', 'middle_name', 'last_name', 'birth_date', 'gender', 'nationality', 'height', 'weight', 'email', 'address', 'city', 'created_at', 'updated_at'];

     public function license()
     {
     	return $this->hasOne('App\DriverLicenseType', 'id', 'license_type_id');
     }

     public function vehicle()
     {
     	return $this->belongsTo('App\Vehicle', 'id', 'driver_id');
     }

     public function violation()
     {
          return $this->belongsTo('App\Violation', 'id', 'driver_id');
     }



     public function getCompleteLastNameAttribute()
     {
     	return $this->last_name . ', ' . $this->first_name . ' ' . $this->middle_name;
     }

     public function getCompleteFirstNameAttribute()
     {
          return $this->last_name . ', ' . $this->first_name . ' ' . $this->middle_name;
     }
}

app/ViolationType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ViolationType extends Model
{
     public $table = 'violation_type';
     public $timestamps = true;

     protected $fillable = [ 'name', 'price', 'created_at', 'updated_at' ];

    public function violation_list()
    {
        return $this->belongsTo('App\ViolationList', 'id', 'violation_type_id');
    }
}

app/Violations.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Violations extends Model
{
     public $table = 'violation';
     public $timestamps = true;

     protected $fillable = [ 'ticket_date', 'remarks', 'driver_id', 'vehicle_id', 'violation_type_id', 'user_id', 'created_at', 'updated_at' ];

    public function driver()
    {
        return $this->hasOne('App\Driver', 'id', 'driver_id');
    }

    public function vehicle()
    {
        return $this->hasOne('App\Vehicle', 'id', 'vehicle_id');
    }

    public function list()
    {
        return $this->belongsTo('App\ViolationList', 'id', 'violation_id');
    }

    public function user()
    {
        return $this->hasOne('App\User', 'id', 'user_id');
    }
}

app/Http/Controllers/ViolationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use thiagoalessio\TesseractOCR\TesseractOCR;
use Auth;
use DB;
use Image;
use Storage;
use App\User;
use App\Driver;
use App\Vehicle;
use App\Violations;
use App\ViolationType;
use App\ViolationList;
use \Carbon\Carbon;

class ViolationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('AdminAccess', ['only' => ['create', 'store', 'edit', 'update']]);
    }

    public function index(Request $request)
    {
        /*$pix = public_path('images\index.png');
        $exe = 'C:\Program Files\Tesseract-OCR\tesseract.exe';
        $ocr = new TesseractOCR($pix);
        $ocr->executable($exe);
        $ocr->lang('eng');
        dd($ocr->run());
        return view('violations.index');*/

        $search = '';

        if($request->has('search'))
        {
            $search = $request->search;
        }

        $rows = Violations::with(['driver', 'vehicle'])
                ->where(function($query) use ($search){
                    $query->whereHas('driver', function($query) use ($search){
                        $query->where('first_name', 'LIKE', "$search%")
                            ->orWhere('middle_name', 'LIKE', "$search%")
                            ->orWhere('last_name', 'LIKE', "$search%");
                    });

                })
                ->orWhere(function($query) use ($search){
                    $query->whereHas('vehicle', function($query) use ($search){
                        $query->where('plate_number', 'LIKE', "$search%")
                                ->orWhere('mv_file_number', 'LIKE', "$search%");
                    });
                })
                ->paginate(100);

        $data = compact('rows', 'search');

        return view('violations.index', $data);
    }
    
    public function create(Request $request)
    {
        $route = route('violations.store');
    	$ticket_date = old('ticket_date');
    	$remarks = old('remarks');
        $driver_name = old('driver_name');
        $license_number = old('license_number');
        $plate_number = old('plate_number', $request->capture);
        $violation_list = old('violation_list');
        #dd($violation_list);
        $route_upload = route('violation_process');

        $violations = ViolationType::get();

    	$data = compact('route', 'ticket_date', 'remarks', 'driver_name', 'license_number', 'plate_number', 'violation_list', 'violations', 'route_upload');

        return view('violations.create-form', $data);
    }
    
    public function store(Requests\ViolationsStoreRequest $request)
    {
        $row1 = Driver::whereLicenseNumber($request->license_number)->first();
        $row2 = Vehicle::wherePlateNumber($request->plate_number)->first();
        $n = 0;
        $input_list = [];
        $input = $request->only(['ticket_date', 'remarks']);
        $input['driver_id'] = $row1->id;
        $input['vehicle_id'] = $row2->id;
        $input['user_id'] = Auth::user()->id;
        $now = Carbon::now();

        $row = Violations::create($input);

        foreach ($request->violation_list as $key => $value)
        {
            $vt = ViolationType::whereId($key)->first();
            $input_list[$n] = [
                'violation_id' => $row->id, 
                'violation_type_id' => $key,
                'price' => $vt->price,
                'created_at' => $now, 
                'updated_at' => $now
            ];
            $n++;
        }

        ViolationList::insert($input_list);

        return redirect()->route('violations.create')->with('success', 'Driver violation successfully added!');
    }
    
    public function edit($id)
    {
    	$route = route('violations.update', $id);
        $row = Violations::whereId($id)->first();
        #dd($row->list->type->get());
    	$ticket_date = $row->ticket_date;
    	$remarks = $row->remarks;
    	$driver_name = $row->driver->complete_last_name;
    	$license_number = $row->driver->license_number;
        $plate_number = $row->vehicle->plate_number;
        $violation_list = [];
        foreach ($row->list->whereViolationId($row->id)->get() as $violation)
        {
            $violation_list[$violation->type->id] = $violation->type->id.'`'.$violation->type->name;
        }

        $violations = ViolationType::get();

        $data = compact('route', 'ticket_date', 'remarks', 'driver_name', 'license_number', 'plate_number', 'violation_list', 'violations');

        return view('violations.create-form', $data);
    }
    
    public function update($id, Requests\ViolationsUpdateRequest $request)
    {
        $row1 = Driver::whereLicenseNumber($request->license_number)->first();
        $row2 = Vehicle::wherePlateNumber($request->plate_number)->first();
        $n = 0;
        $input_list = [];
        $input = $request->only(['ticket_date', 'remarks']);
        $input['driver_id'] = $row1->id;
        $input['vehicle_id'] = $row2->id;
        $input['user_id'] = $row2->id;
        $now = Carbon::now();
        Violations::whereId($id)->update($input);

        foreach ($request->violation_list as $key => $value)
        {
            $input_list[$n] = [
                'violation_id' => $id, 'violation_type_id' => $key,
                'price' => $vt->price,
                'created_at' => $now, 'updated_at' => $now
            ];
            $n++;
        }

        ViolationList::whereViolationId($id)->delete();
        ViolationList::insert($input_list);

        return redirect()->route('violations.edit', $id)->with('success', 'Driver violation successfully updated!');
    }
    
    public function show($id)
    {
        $row = Violations::whereId($id)->first();
        $ticket_date = $row->ticket_date;
        $remarks = $row->remarks;
        $driver_name = $row->driver->complete_last_name;
        $license_number = $row->driver->license_number;
        $plate_number = $row->vehicle->plate_number;
        $violation_list = [];
        foreach ($row->list->whereViolationId($row->id)->get() as $violation)
        {
            $violation_list[$violation->type->id] = $violation->type->id.'`'.$violation->type->name;
        }

        $data = compact('ticket_date', 'remarks', 'driver_name', 'license_number', 'plate_number', 'violation_list');

        return view('violations.show', $data);
    }
    
    public function upload_form()
    {
        $route = route('violation_process');

        $data = compact('route');

        return view('violations.upload', $data);
    }

    public function process_image(Request $request)
    {
        $request->validate([
            'photo' => 'required|image'
        ]);

        $file           = $request->photo;
        $extension      = $file->getClientOriginalExtension();
        $size           = $file->getClientSize();
        $file_name      = date('Ymdhis') . '_' . str_random(10) . '.' . $extension;
        $file_location  = public_path('images/captures/' . $file_name);

        $image = Image::make($file->getRealPath());
        #$image->invert();
        $image->greyscale();
        #$image->crop(280, 100, 15, 35);
        /*$image->resize(100, null, function ($constraint){
            $constraint->aspectRatio();
        });*/
        $image->save($file_location);

        $pix = $file_location;
        $exe = '';
        $exe1 = 'C:\Program Files(x64)\Tesseract-OCR\tesseract.exe';
        $exe2 = 'C:\Program Files\Tesseract-OCR\tesseract.exe';

        if(file_exists($exe1))
        {
            $exe = $exe1;
        }
        else
        {
            $exe = $exe2;
        }

        $ocr = new TesseractOCR($pix);
        $ocr->executable($exe);
        $ocr->lang('eng');
        //$ocr->whitelist(range('a', 'z'), range(0, 9), '-_@');
        $capture = strtoupper(trim($ocr->run()));

        /*$capture = str_replace("\n", '', $capture);
        $capture = str_replace("\r", '', $capture);
        $capture = str_replace("\"", '', $capture);
        $capture = str_replace("\'", '', $capture);*/

        #dd($capture);
        //Image::make($file->getRealPath())->resize(190, 190)->save($file_location);
        #$pix = public_path('images\test1.png');
        #echo $capture;exit;
        /*$count = Vehicle::wherePlateNumber($capture)->count();

        if($count <= 0)
        {
            #return redirect()->route('violation_upload')->with('warning', 'Plate Number does not exists!');
            return redirect()->route('violations.create')->with('warning', 'Plate Number does not exists!');
        }*/

        return redirect()->route('violations.create', [ 'capture' => $capture ]);
    }
}

resources/views/violations/index.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="columns">
        <div class="column is-9">
            <h3 class="title is-3"><i class="fa fa-exclamation-triangle"></i> Violations</h3>
        </div>
        <div class="column is-3">
            <form action="" method="get">
                <div class="field has-addons">
                    <div class="control">
                        <a class="button is-static"><i class="fa fa-search"></i></a>
                    </div>
                    <div class="control">
                        <input class="input is-normal" type="text" name="search" id="search" value="{{ $search }}">
                    </div>
                    <div class="control">
                        <button class="button is-dark">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table is-bordered is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr>
                <td width="5%"></td>
                <td width="25%">Driver</td>
                <td width="10%">Plate Number</td>
                <td width="20%">Violation</td>
                <td width="10%">Amount</td>
                <td width="10%">Date</td>
                <td width="20%">Officer</td>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $violation)
            <?php $penalty_amout = 0; ?>
            <tr>
                <td class="has-text-centered">
                    @if(Auth::user()->access == 1)
                    <a href="{{ route('violations.edit', $violation->id) }}" title="Edit violations details">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a href="{{ route('violations.show', $violation->id) }}" title="Show violations details">
                        <i class="fa fa-list-alt"></i>
                    </a>
                    @else
                    <i class="fa fa-edit"></i>
                    <i class="fa fa-list-alt"></i>
                    @endif
                </td>
                <td>
                    <a href="{{ route('drivers.show', $violation->driver_id) }}" title="Click to show driver details">
                        {{ $violation->driver->complete_last_name }}
                    </a>
                </td>
                <td>
                    <a href="{{ route('vehicles.show', $violation->vehicle_id) }}" title="Click to show vehicle details">
                        {{ $violation->vehicle->plate_number }}
                    </a>
                </td>
                <td>
                    @foreach($violation->list->whereViolationId($violation->id)->get() as $row)
                        <u>{{ $row->type->name }}</u>
                        <?php $penalty_amout += $row->type->price; ?>
                    @endforeach
                </td>
                <td>{{ number_format($penalty_amout, 2) }}</td>
                <td>{{ $violation->ticket_date }}</td>
                <td>{{ $violation->user->name }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {!! $rows->appends(['search'=>$search])->links('vendor.pagination.default') !!}
        
@endsection

resources/views/violations/show.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ route('violations.index') }}">Violations</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Details</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            <div class="columns">
                <div class="column is-8">
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label" for="driver_name">Driver</label>
                        </div>
                        <div class="field-body">
                            <div class="field is-expanded">
                                <p class="control">
                                    {{ $driver_name }}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label" for="driver_name">License No.</label>
                        </div>
                        <div class="field-body">
                            <div class="field is-expanded">
                                <p class="control">
                                    {{ $license_number }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label" for="ticket_date">Vehicle</label>
                        </div>
                        <div class="field-body">
                            <div class="field is-narrow">
                                <p class="control">
                                    {{ $plate_number }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label" for="ticket_date">Ticket Date</label>
                        </div>
                        <div class="field-body">
                            <div class="field is-narrow">
                                <p class="control">
                                    {{ date('F d, Y', strtotime($ticket_date)) }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label class="label" for="remarks">Remarks</label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control is-expanded">
                                    {{ $remarks }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="column is-4">
                    <table id="violations" class="table is-bordered is-narrow is-hoverable is-fullwidth">
                        <thead>
                            <tr>
                                <th width="100%">Violation</th>
                            </tr>
                        </thead>
                        <tbody>
                        @if($violation_list)
                            @foreach($violation_list as $value)
                                <?php
                                $row = explode("`", $value);
                                ?>
                                <tr class="violation-row-{{ $row[0] }}">
                                    <td>
                                        {{ $row[1] }}
                                        <input type="hidden" class="violations_list" name="violation_list[{{ $row[0] }}]" value="{{ $value }}">
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/violations/upload.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="#">Violations</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Upload Image</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            @include('layouts.validation-messages')
            <div class="content">
    
                <form action="{{ $route }}" method="post" enctype="multipart/form-data">
                    <div class="columns">
                        <div class="column is-9">

                            <div class="field is-horizontal">
                                <div class="field-label is-normal"></div>
                                <div class="field-body">
                                    <div class="file has-name is-centered is-info">
                                        <label class="file-label">
                                            <input class="file-input" type="file" name="photo" accept="image/*">
                                            <span class="file-cta">
                                                <span class="file-icon">
                                                    <i class="fa fa-upload"></i>
                                                </span>
                                                <span class="file-label">Choose a file…</span>
                                            </span>
                                        <span class="file-name">Screen Shot {{ date('Y-m-d @ h:m:i') }}.png</span>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label"></div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="control">
                                            <button class="button is-info is-normal">Submit</button>
                                            {!! csrf_field() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
@endsection