routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$this->get('/', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('login_auth');

Route::prefix('portal')
->middleware('auth')
->group(function(){
	$this->post('logout', 'Auth\LoginController@logout')->name('logout');

	Route::get('users/reset-password', 'UsersController@reset_password_form')->name('reset_password_form');
	Route::post('users/reset-password', 'UsersController@reset_password')->name('reset_password');

	Route::get('/', 'HomeController@index')->name('home');
	Route::get('drivers/search', 'DriverController@json_search')->name('json_search');
	Route::resource('drivers', 'DriverController');
	Route::resource('vehicles', 'VehicleController');

	Route::prefix('settings')
	->middleware('AdminAccess')
	->group(function(){
		Route::resource('violation-type', 'ViolationTypeController');
		Route::resource('vehicle-body-type', 'VehicleBodyTypeController');
		Route::resource('fuel', 'FuelController');

		Route::get('users/generate-password', 'UsersController@generate_password')->name('generate_password');
		Route::resource('users', 'UsersController');
	});
	
	Route::get('violations/upload', 'ViolationsController@upload_form')->name('violation_upload');
	Route::post('violations/upload', 'ViolationsController@process_image')->name('violation_process');
	Route::resource('violations', 'ViolationsController');

	Route::prefix('reports')
	->group(function(){
		Route::resource('report-violation', 'ReportViolationController');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'access', 'active', 'created_at', 'updated_at'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getAccessStatusAttribute()
    {
    	if($this->access == 1)
    	{
    		return 'ADMIN';
    	}
    	return 'NORMAL';
    }

    public function getActiveStatusAttribute()
    {
    	if($this->active == 1)
    	{
    		return 'YES';
    	}
    	return 'NO';
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;
use Auth;

class UsersController extends Controller
{
    public function index(Request $request)
    {
        $search = '';

        if($request->has('search'))
        {
            $search = $request->search;

        }

        $rows = User::where('name', 'LIKE', "$search%")->orWhere('email', 'LIKE', "$search%")->paginate(100);

        $data = compact('rows', 'search');

        return view('user.index', $data);
    }
    
    public function create()
    {
    	$name = old('name');
    	$email = old('email');
    	$access = old('access');
    	$active = old('active');
    	$route = route('users.store');

    	$data = compact('route', 'name', 'email', 'access', 'active');

        return view('user.create-form', $data);
    }
    
    public function store(Requests\UsersStoreRequest $request)
    {
        #dd($request->all());
        $input = $request->except('_token');
        $input['password'] = bcrypt('p@ssw0rd');

        User::create($input);
        
        return redirect()->route('users.create')->with('success', 'User Successfully added!');
    }
    
    public function edit($id)
    {
    	$route = route('users.update', $id);
        $row = User::whereId($id)->first();
    	$name = $row->name;
    	$email = $row->email;
    	$access = $row->access;
    	$active = $row->active;

    	$data = compact('route', 'name', 'email', 'access', 'active');

        return view('user.create-form', $data);
    }
    
    public function update($id, Request $request)
    {
        #dd($request->all());   
        $input = $request->except('_token', '_method', 'password');

        User::whereId($id)->update($input);

        return redirect()->route('users.edit', $id)->with('success', 'User Successfully updated!');
    }
    
    public function show($id)
    {
        $row = User::whereId($id)->first();
        $name = $row->name;
        $email = $row->email;
        $access = $row->access;
        $active = $row->active;

        $data = compact('name', 'email', 'access', 'active');

        return view('user.show', $data);
    }

    public function generate_password(Request $request)
    {
        $password = str_random(10);

        User::whereId($request->id)->update([ 'password'=>bcrypt($password) ]);

        return response()->json([ 'password'=>$password ]);
    }

    public function reset_password_form()
    {
        $route = route('reset_password');

        $data = compact('route');

        return view('user.reset', $data);
    }

    public function reset_password(Request $request)
    {
        $request->validate([
            'password' => 'required',
            'confirm_password' => 'required|same:password'
        ]);

        $password = bcrypt($request->password);

        User::whereId(Auth::user()->id)->update([ 'password'=>$password ]);

        return redirect()->route('reset_password_form')->with('success', 'Password Successfully changed!');
    }
}

resources/views/user/create-form.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ route('users.index') }}">User</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Form</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            @include('layouts.validation-messages')
            <div class="content">
                <form action="{{ $route }}" method="post">

                    <div class="columns">
                        <div class="column is-7">

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="name">Name</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="text" name="name" id="name" value="{{ $name }}">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="email">E-Mail</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="email" name="email" id="email" value="{{ $email }}">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="access">Access</label>
                                </div>
                                <div class="field-body">
                                    <div class="field is-narrow">
                                        <div class="control">
                                            <div class="select is-fullwidth">
                                                <select name="access" id="access">
                                                    <option value="1">Admin</option>
                                                    <option value="2">Normal</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="access">Active</label>
                                </div>
                                <div class="field-body">
                                    <div class="field is-narrow">
                                        <div class="control">
                                            <div class="select is-fullwidth">
                                                <select id="active" name="active">
                                                    <option value="0">No</option>
                                                    <option value="1">Yes</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            @if(Request::segment(5) == 'edit')
                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="name">Password</label>
                                </div>
                                <div class="field-body">
                                    <div class="field has-addons">
                                        <div class="control">
                                        </div>
                                        <div class="control">
                                            <input class="input is-normal" type="text" name="password" id="password" value="" readonly="">
                                        </div>
                                        <div class="control">
                                            <a href="javascript:void(0)" onclick="generate_password({{ Request::segment(4) }})" class="button is-dark"><i class="fa fa-refresh"></i>&nbsp;&nbsp;Generate</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {{ method_field('PUT') }}
                            @endif

                            <div class="field is-horizontal">
                                <div class="field-label"></div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="control">
                                            <button class="button is-info is-normal">Submit</button>
                                            {!! csrf_field() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<input type="hidden" id="generate_password" value="{{ route('generate_password') }}">
<script type="text/javascript">
    var xhr_generate_password = null;

    $('#access option[value={{ $access or 0 }}]').attr('selected','selected');
    $('#active option[value={{ $active or 0 }}]').attr('selected','selected');

    function generate_password(id)
    {
        xhr_generate_password = $.ajax({
            type : 'get',
            url : $("#generate_password").val(),
            data : 'id=' + id,
            dataType : "json",
            beforeSend: function(xhr) 
            {
                if (xhr_generate_password != null)
                {
                    xhr_generate_password.abort();
                }
            }
        }).done(function(data) 
        {
            $('#password').val(data['password']);
        }).fail(function(jqXHR, textStatus) 
        {
            //console.log('Request failed: ' + textStatus);
        });
    }
</script>
@endpush

resources/views/user/index.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="columns">
        <div class="column is-9">
            <h3 class="title is-3"><i class="fa fa-users"></i> Users</h3>
        </div>
        <div class="column is-3">
            <form action="" method="get">
                <div class="field has-addons">
                    <div class="control">
                        <a class="button is-static"><i class="fa fa-search"></i></a>
                    </div>
                    <div class="control">
                        <input class="input is-normal" type="text" name="search" id="search" value="{{ $search }}">
                    </div>
                    <div class="control">
                        <button class="button is-dark">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table is-bordered is-narrow is-hoverable is-fullwidth">
        <thead>
            <tr>
                <td width="5%"></td>
                <td width="25%">Name</td>
                <td width="20%">Email</td>
                <td width="10%">Access</td>
                <td width="10%">Active</td>
                <td width="15%">Created At</td>
                <td width="15%">Updated At</td>
            </tr>
        </thead>
        <tbody>
            @foreach($rows as $row)
            <tr>
                <td class="has-text-centered">
                    @if(Auth::user()->access == 1)
                    <a href="{{ route('users.edit', $row->id) }}" title="Edit User Details">
                        <i class="fa fa-edit"></i>
                    </a>
                    @else
                        <i class="fa fa-edit"></i>
                    @endif
                    <a href="{{ route('users.show', $row->id) }}" title="Show User Details">
                        <i class="fa fa-list-alt"></i>
                    </a>
                </td>
                <td>{{ $row->name }}</td>
                <td>{{ $row->email }}</td>
                <td>{{ $row->access_status }}</td>
                <td>{{ $row->active_status }}</td>
                <td>{{ $row->created_at }}</td>
                <td>{{ $row->updated_at }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    {!! $rows->appends(['search'=>$search])->links('vendor.pagination.default') !!}
        
@endsection

resources/views/user/reset.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li class="is-active"><a href="#" aria-current="page">Reset Password</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            @include('layouts.validation-messages')
            <div class="content">
                <form action="{{ $route }}" method="post">

                    <div class="columns">
                        <div class="column is-10">

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="password">Password</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="password" name="password" id="password" value="">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label is-normal">
                                    <label class="label is-normal" for="confirm_password">Confirm Password</label>
                                </div>
                                <div class="field-body">
                                    <div class="field">
                                        <p class="control is-expanded">
                                            <input class="input is-normal" type="password" name="confirm_password" id="confirm_password" value="">
                                        </p>
                                    </div>
                                </div>
                            </div>

                            <div class="field is-horizontal">
                                <div class="field-label"></div>
                                <div class="field-body">
                                    <div class="field">
                                        <div class="control">
                                            <button class="button is-info is-normal">Submit</button>
                                            {!! csrf_field() !!}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.master')

@section('content')
    <br>
    <div class="card">
        <header class="card-header">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <nav class="breadcrumb" aria-label="breadcrumbs">
                <ul>
                    <li><a href="{{ route('users.index') }}">User</a></li>
                    <li class="is-active"><a href="#" aria-current="page">Details</a></li>
                </ul>
            </nav>
        </header>
        <div class="card-content">
            <div class="content">

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" >Name</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $name }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="email">E-Mail</label>
                    </div>
                    <div class="field-body">
                        <div class="field">
                            <p class="control is-expanded">
                                {{ $email }}
                            </p>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="access">Access</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-narrow">
                            <div class="control">
                                {{ $access }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="field is-horizontal">
                    <div class="field-label">
                        <label class="label" for="access">Active</label>
                    </div>
                    <div class="field-body">
                        <div class="field is-narrow">
                            <div class="control">
                                {{ $access }}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection